### ISSUE TITLE
[CaptionMod] Some Subtitles are not playing in base Half-Life and none are playing in Opposing Force

### ISSUE THREAD

**Issue by Zaphero1** [hzqst/MetaHookSv#226]
Just from the start the second line of dialog in base Half-Life, giving what time it is, is not subtitled and Opposing Force doesn't seem to have subtitles at all based on the start of both the campaign and the training mode, and toggling the options like Antispam and wait queued lines for CaptionMod doesn't seem to affect that.

**Comment by Zaphero1** [comment]
The subtitle in question is in dictionary_english.txt, but does not play:
`"c0a0_tr_time"	"The time is 08:47 AM. Current topside temperature is 93 degrees, with an estimated high of one hundred and five. The Black Mesa compound is maintained at a pleasant 68 degrees at all times."`

**Comment by hzqst** [comment]
Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230111

**Comment by hzqst** [comment]
As for opfor subtitles, you probably looking for https://github.com/qabRieL99/HalfLifeSerisiTurkce/blob/0301895f035c6181e2baecd68088bf26c1123702/gearbox/CaptionMod/gearboxing.txt

Installation:

Rename to `dictionary_english.txt` and move to `/Half-Life/gearbox/captionmod/`

**Comment by Zaphero1** [comment]
> As for opfor subtitles, you probably looking for https://github.com/qabRieL99/HalfLifeSerisiTurkce/blob/0301895f035c6181e2baecd68088bf26c1123702/gearbox/CaptionMod/gearboxing.txt
> 
> Installation:
> 
> Rename to `dictionary_english.txt` and move to `/Half-Life/gearbox/captionmod/`

I'm afraid that just made the game crash on startup.
![image](https://user-images.githubusercontent.com/19298996/211952866-21e1f90c-da68-4e0a-93ab-9bb86f75d7ab.png)

**Comment by Zaphero1** [comment]
> Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20230111
Ah I haven't seen a subtitle missed yet now, so far so good.

**Comment by Zaphero1** [comment]
Opposing Force is still crashing on startup with that dictionary_english.txt though.

**Comment by hzqst** [comment]
> Opposing Force is still crashing on startup with that dictionary_english.txt though.

The directory hierarchy is supposed to be like this :
![2222](https://user-images.githubusercontent.com/12287588/211960776-724d9a19-e88b-47a6-b06f-14fa1765ceab.png)

works fine for me at least.

Don't forget to replace `dictionary.csv` with [this one](https://github.com/qabRieL99/HalfLifeSerisiTurkce/blob/0301895f035c6181e2baecd68088bf26c1123702/gearbox/CaptionMod/dictionary.csv), and `dictionary_english.txt` with [this one](https://github.com/qabRieL99/HalfLifeSerisiTurkce/blob/0301895f035c6181e2baecd68088bf26c1123702/gearbox/CaptionMod/gearboxing.txt)

**Comment by Zaphero1** [comment]
Ah after adding that csv file and giving downloading that dictionary_english.txt as a second shot it works! Thank you very much!
